
title: "Next Bonnie"
subtitle: "Exploring learnings as I embrace the next iteration of my career"
email: barnali.c@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 This blog documents my journey in Customer Experience. It also documents how an immigrant Indian woman found a new career in the middle of Silicon Valley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nextbonnie.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: barnali_c
github_username:  bonniec

author:
  name     : "Bonnie Chatterjee"
  avatar   : "/assets/images/bonniec.jpg"
  bio      : "Head of Customer Experience at GitHub"
  location : "California, USA"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/barnali_c"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bonniec"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/barnalic/"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      author_profile: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
